### ISSUE TITLE
Middleware doesn't work with createFarceRouter

### ISSUE THREAD

**Issue by cutamar** [4Catalyzer/found-named-routes#153]
Seems this doesn't work with `createFarceRouter`. I get the following error:  
`TypeError: matcher.routeConfig.forEach is not a function` in `createMatcherNamedRoutesMiddleware.js:59`

**Comment by taion** [comment]
Do you have more details on how you're using this?

**Comment by cutamar** [comment]
@taion same as in this sample https://github.com/relay-tools/found-relay#router-configuration  
set names for the routes, and added the middleware from `found-named-routes` to `historyMiddlewares`. That's all I did

**Comment by taion** [comment]
What are you passing in for the route config to `createNamedRoutesMiddleware`? If you're using JSX routes, then it should be the output of `makeRouteConfig`.

**Comment by cutamar** [comment]
I missed the fact, that `createNamedRoutesMiddleware` needs the `routeConfig`, and used the middleware function direclty. Fixed it now, and works really well. Thanks for the fast support, and sorry for wasting your time, by not reading the instructions carefully.

**Comment by taion** [comment]
don't worry about it! i'm clarifying things in the README a bit in https://github.com/4Catalyzer/found-named-routes/pull/154

**Comment by cutamar** [comment]
Adding types would also be a big help for all typescript users, then errors like this couldn't happen. For this package I wrote the type def myself, and it looks like this:
```typescript
declare module 'found-named-routes' {
    import Middleware from 'farce';
    import RouteConfig from 'found';

    const createNamedRoutesMiddleware = (routeConfig: RouteConfig) => Middleware;
}
```
Only problem is, that it depends on farce in this case.

**Comment by taion** [comment]
You're right. I need to find time to get https://github.com/4Catalyzer/farce/pull/175 merged, too.
