### ISSUE TITLE
Can't redirect to absolute urls

### ISSUE THREAD

**Issue by NSLS** [4Catalyzer/found-named-routes#56]
After adding this middleware in one of our projects, we have faced a problem that all of our absolute redirects have stopped working.

It seems like this line is the cause of this issue:
https://github.com/4Catalyzer/found-named-routes/blob/master/src/createMatcherNamedRoutesMiddleware.js#L38

I assume, that we need to add another check for the location being an absolute URL over here. 

If you agree, I could make a quick PR for this

**Comment by NSLS** [comment]
Decided not to wait and submitted a PR #57

**Comment by taion** [comment]
fixed in #57

**Comment by NSLS** [comment]
Great thanks, @taion!

**Comment by taion** [comment]
might be a little bit until i can publish, unfortunately. the person with publish permissions is traveling right now

**Comment by NSLS** [comment]
It's ok, we can wait, thank you!
